export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ik1hcmlhbmEgTW9yw6NlcyIsImVtYWlsIjoibWFyaWFuYUBnbWFpbC5jb20iLCJpYXQiOjE2ODIwMDkxNDYsImV4cCI6MTY4MjYxMzk0NiwiYXVkIjoidXNlcnMiLCJpc3MiOiJsb2dpbiIsInN1YiI6IjEifQ.6UZcluVEJM1xdUauTn2hdkwlUm0GQbl7DzcquFZ0Oso';
